https://colab.research.google.com/drive/1oZxjgfxLE1RXPRo8aMz6Yva1urUB9tzU?usp=sharing

#CP 2.2.1 b

In [10]:
#CP 2.2.1 b
import numpy as np
import copy
from math import sqrt
import numpy as np
import scipy
from scipy.optimize import fsolve
from scipy.optimize import root


def lu_no_pivoting( A_ ):
  A = copy.deepcopy(A_)
#
  n = A.shape[0]
  for k in range(0,n-1):
    if ( A[k,k] == 0. ): print("oops, zero pivot encountered\n"); break
    for i in range(k+1,n):
      A[i,k] = A[i,k] / A[k,k]
      for j in range(k+1,n):
        A[i,j] = A[i,j] - A[k,j] * A[i,k]
#
  L = np.tril(A,-1)+np.eye(n)
  U = np.triu(A)
  return L, U

A = np.array([  [  4.,  2.,  0. ],
                [  4.,  4.,  2. ],
                [  2.,  2.,  3. ] ] )

L, U = lu_no_pivoting ( A )
print("L=\n",L)
print("U=\n",U)
# check that A = LU
print("\nL @ U=\n", L @ U)
print("A=\n",A)
print("\n | | A − LU | | oo / | | A | | oo = " ,\
np.linalg.norm(A - L@U ,np.inf )/np.linalg.norm(A,np.inf) )

L=
 [[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.5 1. ]]
U=
 [[4. 2. 0.]
 [0. 2. 2.]
 [0. 0. 2.]]

L @ U=
 [[4. 2. 0.]
 [4. 4. 2.]
 [2. 2. 3.]]
A=
 [[4. 2. 0.]
 [4. 4. 2.]
 [2. 2. 3.]]

 | | A − LU | | oo / | | A | | oo =  0.0


#2.2.1 c

In [11]:
#2.2.1 c
A = np.array([  [  1.,  -1.,  1., 2 ],
                [  0.,  2.,  1., 0. ],
                [  1.,  3.,  4., 4. ],
                [  0.,  2.,  1., -1. ]] )

L, U = lu_no_pivoting ( A )
print("L=\n",L)
print("U=\n",U)
# check that A = LU
print("\nL @ U=\n", L @ U)
print("A=\n",A)
print("\n | | A − LU | | oo / | | A | | oo = " ,\
np.linalg.norm(A - L@U ,np.inf )/np.linalg.norm(A,np.inf) )

L=
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 2. 1. 0.]
 [0. 1. 0. 1.]]
U=
 [[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0. -1.]]

L @ U=
 [[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 1.  3.  4.  4.]
 [ 0.  2.  1. -1.]]
A=
 [[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 1.  3.  4.  4.]
 [ 0.  2.  1. -1.]]

 | | A − LU | | oo / | | A | | oo =  0.0


#CP 2.2.2.b


In [12]:
#CP 2.2.2.b
import numpy as np
import copy
from math import sqrt
import numpy as np
import scipy
from scipy.optimize import fsolve
from scipy.optimize import root


def lu_no_pivoting( A_ ):
  A = copy.deepcopy(A_)
#
  n = A.shape[0]
  for k in range(0,n-1):
    if ( A[k,k] == 0. ): print("oops, zero pivot encountered\n"); break
    for i in range(k+1,n):
      A[i,k] = A[i,k] / A[k,k]
      for j in range(k+1,n):
        A[i,j] = A[i,j] - A[k,j] * A[i,k]
#
  L = np.tril(A,-1)+np.eye(n)
  U = np.triu(A)
  return L, U

def backward_substitution( A, b_ ):
  b = copy.deepcopy(b_)
  n = A.shape[0]
  for i in range(n-1,-1,-1):
    for j in range(i+1,n):
      b[i] = b[i] - A[i,j] * b[j]
    b[i] = b[i] / A[i,i]
  return b

def forward__substitution( A, b_ ):
  b = copy.deepcopy(b_)
  n = A.shape[0]
  for i in range(0,n,):
    for j in range(0,i):
      b[i] = b[i] - A[i,j] * b[j]
    b[i] = b[i] / A[i,i]
  return b

# Define A and b outside the function
A = np.array ([ [ 4., 2., 0. ],
                [ 4., 4., 2. ],
                [ 2., 2., 3. ] ] )

b = np.array ([ [ 2. ],
                [ 4. ],
                [ 6. ] ] )

# solve Ax=b with np.linalg.solve
# and check that Ax is b

x = np.linalg.solve(A, b)

print("With np.linalg.solve, we find x = \n", x)

print("\nWe check that Ax is b. Indeed [ Ax, b ] =\n", np.concatenate((A@x, b), axis=1) )

print("\nrelative backward error: || b - Ax  ||_oo / || b ||_oo =\n", np.linalg.norm(b-A@x,np.inf)/np.linalg.norm(b,np.inf) )

# using our bucket algorithms
#   `lu_no_pivoting`
#   `forward__substitution`
#   `backward_substitution`

L, U = lu_no_pivoting( A )
y = forward__substitution( L, b )
x = backward_substitution( U, y )

print("With our algorithms, we find\n")
print("y=\n",y)
print("x=\n",x)

print("\nWe check that Ax is b. Indeed [ Ax, b ] =\n", np.concatenate((A@x, b), axis=1) )

print("\nrelative backward error: || b - Ax  ||_oo / || b ||_oo =\n", np.linalg.norm(b-A@x,np.inf)/np.linalg.norm(b,np.inf) )

With np.linalg.solve, we find x = 
 [[ 1.]
 [-1.]
 [ 2.]]

We check that Ax is b. Indeed [ Ax, b ] =
 [[2. 2.]
 [4. 4.]
 [6. 6.]]

relative backward error: || b - Ax  ||_oo / || b ||_oo =
 0.0
With our algorithms, we find

y=
 [[2.]
 [2.]
 [4.]]
x=
 [[ 1.]
 [-1.]
 [ 2.]]

We check that Ax is b. Indeed [ Ax, b ] =
 [[2. 2.]
 [4. 4.]
 [6. 6.]]

relative backward error: || b - Ax  ||_oo / || b ||_oo =
 0.0


#2.3.6

In [13]:
#2.3.6

A = np.array([
                 [  1., 2.  ],
                 [  2., 4.01]])

b = np.array([[3.],[6.01]])
# First off, we can find the solution right away.
# The solution is x1 = 1 and x2 = -1.
# Let us check this.

x = np.linalg.solve(A, b)
print("|| b - Ax ||_oo / || b ||_oo = ",\
      f"{np.linalg.norm(b-A@x,np.inf)/np.linalg.norm(b,np.inf)}")

# (e) What is the condition number of the coefficient matrix?

K = np.linalg.norm(A,np.inf)*np.linalg.norm(np.linalg.inv(A),np.inf)
print("kappa(A) = ", f"{K:6.1f}")

# Find the relative forward and backward errors and error magnification factor
# for the following approximate solutions of the system
# (a) [ -10 ]  (b) [ -100 ]  (c) [  -600 ]  (d) [ -599 ]
#     [ 6 ]      [ 52 ]      [ 301 ]      [ 301 ]

for xa in [ np.array([[-10.],[6.]]),\
            np.array([[-100.],[52.]]),\
            np.array([[ -600.],[301.]]),\
            np.array([[-599.],[301.]]) ]:
  relative_forward_error = np.linalg.norm( x - xa, np.inf )\
     / np.linalg.norm( x, np.inf )
  relative_backward_error = np.linalg.norm( b - A@xa, np.inf )\
    / np.linalg.norm( b, np.inf )
  error_magnification_factor = relative_forward_error\
    / relative_backward_error
  print( "xa = [ ",f"{xa[0,0]:.0f}",",",f"{xa[1,0]:.0f}","]" )
  print( "relative forward error     = ",\
    f"{relative_forward_error:8.2f}" )
  print( "relative backward error    = ",\
    f"{relative_backward_error:8.2f}" )
  print( "error magnification factor = ",\
   f"{error_magnification_factor:8.2f}" )
  print("\n")

|| b - Ax ||_oo / || b ||_oo =  0.0
kappa(A) =  3612.0
xa = [  -10 , 6 ]
relative forward error     =     11.00
relative backward error    =      0.32
error magnification factor =     33.90


xa = [  -100 , 52 ]
relative forward error     =    101.00
relative backward error    =      0.42
error magnification factor =    241.84


xa = [  -600 , 301 ]
relative forward error     =    601.00
relative backward error    =      0.17
error magnification factor =   3612.01


xa = [  -599 , 301 ]
relative forward error     =    600.00
relative backward error    =      0.50
error magnification factor =   1202.00




#2.3.4

In [14]:
n = 5
A = np.zeros( [ n, n ], dtype=float )
for i in range(0,n):
  for j in range(0,n):
      A[i,j] = np.sqrt((i - j)**2 + n / 10)
print(A)

[[0.70710678 1.22474487 2.12132034 3.082207   4.0620192 ]
 [1.22474487 0.70710678 1.22474487 2.12132034 3.082207  ]
 [2.12132034 1.22474487 0.70710678 1.22474487 2.12132034]
 [3.082207   2.12132034 1.22474487 0.70710678 1.22474487]
 [4.0620192  3.082207   2.12132034 1.22474487 0.70710678]]


In [15]:
%%time

for n in range(100,600,100):
  A = np.zeros( [ n, n ] )
  for i in range(0,n):
    for j in range(0,n):
      A[i,j] = abs( i - j ) + 1.
  x = np.ones( [ n, 1 ] )
  b = A @ x

  xc = np.linalg.solve( A, b )

  relative_forward_error = np.linalg.norm( x - xc, np.inf )\
     / np.linalg.norm( x, np.inf )
  relative_backward_error = np.linalg.norm( b - A@xc, np.inf )\
    / np.linalg.norm( b, np.inf )
  error_magnification_factor = relative_forward_error\
    / relative_backward_error
  print( "n = ",f"{n:4d}" )
  print( "relative forward error                      = ",\
    f"{relative_forward_error:8.2e}" )
  print( "relative backward error                     = ",\
    f"{relative_backward_error:8.2e}" )
  print( "error magnification factor                  = ",\
   f"{error_magnification_factor:8.2e}" )
  print( "kappa( A ) = || A ||_oo * || A^{-1} ||_oo   = ",\
   f"{np.linalg.norm(A,np.inf) * np.linalg.norm(np.linalg.inv(A),np.inf):8.2e}")
  print("\n")

n =   100
relative forward error                      =  3.47e-12
relative backward error                     =  8.10e-16
error magnification factor                  =  4.28e+03
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  1.01e+04


n =   200
relative forward error                      =  1.68e-11
relative backward error                     =  8.14e-16
error magnification factor                  =  2.06e+04
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  4.02e+04


n =   300
relative forward error                      =  5.87e-11
relative backward error                     =  1.29e-15
error magnification factor                  =  4.55e+04
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  9.03e+04


n =   400
relative forward error                      =  1.14e-10
relative backward error                     =  1.27e-15
error magnification factor                  =  8.99e+04
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  1.60e+05


n =   500
relative forward error                      = 

In [16]:
import copy
def lu_no_pivoting( A_, inplace = False ):
#
  if ( inplace ):
    A = A_
  else:
    A = copy.deepcopy(A_)
# begin main code
  n = A.shape[0]
  for k in range(0,n-1):
    if ( A[k,k] == 0. ): print("oops, zero pivot encountered\n"); break
    for i in range(k+1,n):
      A[i,k] = A[i,k] / A[k,k]
      for j in range(k+1,n):
        A[i,j] = A[i,j] - A[k,j] * A[i,k]
# end main code
  if not inplace:
    L = np.tril(A,-1)+np.eye(n)
    U = np.triu(A)
    return L, U

def backward_substitution( A, b_, inplace = False ):
#
  if ( inplace ):
    b = b_
  else:
    b = copy.deepcopy(b_)
#
  n = A.shape[0]
  for i in range(n-1,-1,-1):
    for j in range(i+1,n):
      b[i] = b[i] - A[i,j] * b[j]
    b[i] = b[i] / A[i,i]
#
  if not inplace:
    return b

def forward__substitution( A, b_, inplace = False, unit = False ):
  if ( inplace ):
    b = b_
  else:
    b = copy.deepcopy(b_)
#
  n = A.shape[0]
  for i in range(0,n,):
    for j in range(0,i):
      b[i] = b[i] - A[i,j] * b[j]
    if not unit:
      b[i] = b[i] / A[i,i]
#
  if not inplace:
    return b

In [17]:
%%time
for n in range(100,600,100):
  A = np.zeros( [ n, n ] )
  for i in range(0,n):
    for j in range(0,n):
      A[i,j] = abs( i - j ) + 1.
  x = np.ones( [ n, 1 ] )
  b = A @ x

  L, U = lu_no_pivoting( A )
  y = forward__substitution( L, b )
  xc = backward_substitution( U, y )

  relative_forward_error = np.linalg.norm( x - xc, np.inf )\
     / np.linalg.norm( x, np.inf )
  relative_backward_error = np.linalg.norm( b - A@xc, np.inf )\
    / np.linalg.norm( b, np.inf )
  error_magnification_factor = relative_forward_error\
    / relative_backward_error
  print( "n = ",f"{n:4d}" )
  print( "relative forward error                      = ",\
    f"{relative_forward_error:8.2e}" )
  print( "relative backward error                     = ",\
    f"{relative_backward_error:8.2e}" )
  print( "error magnification factor                  = ",\
   f"{error_magnification_factor:8.2e}" )
  print( "kappa( A ) = || A ||_oo * || A^{-1} ||_oo   = ",\
   f"{np.linalg.norm(A,np.inf) * np.linalg.norm(np.linalg.inv(A),np.inf):8.2e}")
  print("\n")

n =   100
relative forward error                      =  5.29e-11
relative backward error                     =  4.23e-14
error magnification factor                  =  1.25e+03
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  1.01e+04


n =   200
relative forward error                      =  5.78e-10
relative backward error                     =  9.19e-14
error magnification factor                  =  6.29e+03
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  4.02e+04


n =   300
relative forward error                      =  3.03e-09
relative backward error                     =  3.49e-13
error magnification factor                  =  8.67e+03
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  9.03e+04


n =   400
relative forward error                      =  4.48e-09
relative backward error                     =  6.40e-13
error magnification factor                  =  7.00e+03
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  1.60e+05


n =   500
relative forward error                      = 

#2.7.1.b


In [18]:
#2.7.1.b
from math import sqrt
import numpy as np
import scipy
from scipy.optimize import fsolve
from scipy.optimize import root

# Define the new system:
F = lambda x: np.array([
    x[0]**2 + 4*x[1]**2 - 4,     # u^2 + 4v^2 - 4 = 0
    4*x[0]**2 + x[1]**2 - 4      # 4u^2 + v^2 - 4 = 0
])

# Two known exact solutions from symmetry (u = ±1, v = ±1)
x1 = np.array([2/np.sqrt(5), 2/np.sqrt(5)])
x2 = np.array([-2/np.sqrt(5), -2/np.sqrt(5)])

# Check backward error
print("|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}")
print("|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}")

# fsolve
for x, x_ in zip([np.array([1.1, 1.1]), np.array([-1.1, -1.1])], [x1, x2]):
    x = fsolve(F, x)
    print("\nx = [", f"{x[0]:+20.16f}", "]     x* = [", f"{x_[0]:+20.16f}", "]")
    print("    [", f"{x[1]:+20.16f}", "]          [", f"{x_[1]:+20.16f}", "]")
    print("forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x - x_, np.inf):7.2e}")
    print("backward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x), np.inf):7.2e}")

# root
for x, x_ in zip([np.array([1.1, 1.1]), np.array([-1.1, -1.1])], [x1, x2]):
    x = root(F, x).x
    print("\nx = [", f"{x[0]:+20.16f}", "]     x* = [", f"{x_[0]:+20.16f}", "]")
    print("    [", f"{x[1]:+20.16f}", "]          [", f"{x_[1]:+20.16f}", "]")
    print("forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x - x_, np.inf):7.2e}")
    print("backward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x), np.inf):7.2e}")

# Newton's Method (Jacobian)
DF = lambda x: np.array([
    [2*x[0], 8*x[1]],           # ∂/∂u and ∂/∂v of equation 1
    [8*x[0], 2*x[1]]            # ∂/∂u and ∂/∂v of equation 2
])

# Run Newton iterations
for x, x_ in zip([np.array([1.5, 1.5]), np.array([-1.5, -1.5])], [x1, x2]):
    print("** Starting Newton's method for:", x_)
    for i in range(6):
        err = np.linalg.norm(x - x_, np.inf)
        res = np.linalg.norm(F(x), np.inf)
        print(f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}", "]", f"{err:4.1e}", f"{res:4.1e}")
        x = x - np.linalg.solve(DF(x), F(x))

    print("\nFinal solution x =\n", x)
    print("forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x - x_, np.inf):7.2e}")
    print("backward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x), np.inf):7.2e}")
    print()


|| F(x1) ||_oo = 4.44E-16
|| F(x2) ||_oo = 4.44E-16

x = [  +0.8944271909999159 ]     x* = [  +0.8944271909999159 ]
    [  +0.8944271909999159 ]          [  +0.8944271909999159 ]
forward  error: || x - x* ||_oo =  0.00e+00
backward error: || F(x) ||_oo   =  4.44e-16

x = [  -0.8944271909999159 ]     x* = [  -0.8944271909999159 ]
    [  -0.8944271909999159 ]          [  -0.8944271909999159 ]
forward  error: || x - x* ||_oo =  0.00e+00
backward error: || F(x) ||_oo   =  4.44e-16

x = [  +0.8944271909999159 ]     x* = [  +0.8944271909999159 ]
    [  +0.8944271909999159 ]          [  +0.8944271909999159 ]
forward  error: || x - x* ||_oo =  0.00e+00
backward error: || F(x) ||_oo   =  4.44e-16

x = [  -0.8944271909999159 ]     x* = [  -0.8944271909999159 ]
    [  -0.8944271909999159 ]          [  -0.8944271909999159 ]
forward  error: || x - x* ||_oo =  0.00e+00
backward error: || F(x) ||_oo   =  4.44e-16
** Starting Newton's method for: [0.89442719 0.89442719]
 0 [  +1.5000000000000000  +1.5

#2.7.1.c


In [19]:
import numpy as np
from scipy.optimize import fsolve, root

# Define F(u, v) for the system
def F(x):
    u, v = x
    return np.array([
        u**2 - 4*v**2 - 4,
        (u-1)**2 + v**2 - 4
    ])

# Analytic Jacobian
def DF(x):
    u, v = x
    return np.array([
        [2*u, -8*v],
        [2*(u-1), 2*v]
    ])

# Exact solutions
u1 = 2.75959
v1 = 0.9507
v2 = -0.9507

x1 = np.array([u1, v1])
x2 = np.array([u1, v2])

print("|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1), np.inf):.2E}")
print("|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2), np.inf):.2E}")

# fsolve and root with two starting points
for x_init, x_true in zip([np.array([2.5, 1.]), np.array([2.5, -1.])], [x1, x2]):
    x_fsolve = fsolve(F, x_init)
    print("\nfsolve:")
    print("x =", x_fsolve)
    print("x* =", x_true)
    print("forward error:", f"{np.linalg.norm(x_fsolve - x_true, np.inf):.2e}")
    print("backward error:", f"{np.linalg.norm(F(x_fsolve), np.inf):.2e}")

    x_root = root(F, x_init).x
    print("root:")
    print("x =", x_root)
    print("x* =", x_true)
    print("forward error:", f"{np.linalg.norm(x_root - x_true, np.inf):.2e}")
    print("backward error:", f"{np.linalg.norm(F(x_root), np.inf):.2e}")

# Newton's method manual implementation
for x_init, x_true in zip([np.array([2.5, 1.0]), np.array([2.5, -1.0])], [x1, x2]):
    print("\nNewton's Method:")
    x = x_init.copy()
    print(f"Start: x = {x}, x* = {x_true}")
    for i in range(6):
        step = np.linalg.solve(DF(x), F(x))
        x = x - step
        print(f"Iter {i+1}: x = {x}, forward error = {np.linalg.norm(x - x_true, np.inf):.2e}, backward error = {np.linalg.norm(F(x), np.inf):.2e}")
    print("Final:")
    print("x =", x)
    print("x* =", x_true)
    print("forward error:", f"{np.linalg.norm(x - x_true, np.inf):.2e}")
    print("backward error:", f"{np.linalg.norm(F(x), np.inf):.2e}")
    print()


|| F(x1) ||_oo = 1.50E-05
|| F(x2) ||_oo = 1.50E-05

fsolve:
x = [2.75959179 0.95070328]
x* = [2.75959 0.9507 ]
forward error: 3.28e-06
backward error: 5.34e-12
root:
x = [2.75959179 0.95070328]
x* = [2.75959 0.9507 ]
forward error: 3.28e-06
backward error: 5.34e-12

fsolve:
x = [ 2.75959179 -0.95070328]
x* = [ 2.75959 -0.9507 ]
forward error: 3.28e-06
backward error: 5.34e-12
root:
x = [ 2.75959179 -0.95070328]
x* = [ 2.75959 -0.9507 ]
forward error: 3.28e-06
backward error: 5.34e-12

Newton's Method:
Start: x = [2.5 1. ], x* = [2.75959 0.9507 ]
Iter 1: x = [2.77941176 0.95588235], forward error = 1.98e-02, backward error = 8.00e-02
Iter 2: x = [2.75969102 0.95073807], forward error = 1.01e-04, backward error = 4.15e-04
Iter 3: x = [2.7595918  0.95070328], forward error = 3.28e-06, backward error = 1.11e-08
Iter 4: x = [2.75959179 0.95070328], forward error = 3.28e-06, backward error = 8.88e-16
Iter 5: x = [2.75959179 0.95070328], forward error = 3.28e-06, backward error = 1.78e-15
It

#2.7.4


In [20]:
#2.7.4
# Copyright (c) 2018, 2012, 2016 by Pearson Education Inc. All Rights Reserved.
# Sauer, Numerical Analysis, 3rd Edition
# Exercise CP.2.7.4

import numpy as np

############################################################################################
# TODO 1: Define the function F for this system of three equations
############################################################################################
def F(x):
    u, v, w = x
    return np.array([
        2*u**2 - 4*u + v**2 + 3*w**2 + 6*w + 2,
        u**2 + v**2 - 2*v + 2*w**2 - 5,
        3*u**2 - 12*u + v**2 + 3*w**2 + 8
    ])

# For debugging, print F at two points (optional)
print("F([1,-1,2]) =", F(np.array([1., -1., 2.])))
print("F([3,5,-4]) =", F(np.array([3., 5., -4.])))

##################################################################################
# TODO 2: Write the Jacobian matrix of F as a function of x = [u,v,w]
##################################################################################
def DF(x):
    u, v, w = x
    return np.array([
        [4*u - 4,   2*v,         6*w + 6],
        [2*u,       2*v - 2,     4*w],
        [6*u - 12,  2*v,         6*w]
    ])

# Print Jacobian at two points for verification (optional)
print("DF([1,-1,2]) =\n", DF(np.array([1., -1., 2.])))
print("DF([3,5,-4]) =\n", DF(np.array([3., 5., -4.])))

##################################################################################
# TODO 3: Find initial guesses for Newton's method that converge to both solutions.
# Here, you may need to try several initial guesses. Start with [2,2,2] and [-2,-2,-2].
##################################################################################

# You may need to tune these starting values to get both solutions!
initial_guesses = [
    np.array([2.0, 2.0, 2.0]),    # likely to converge to one solution
    np.array([-2.0, -2.0, -2.0])  # likely to converge to another solution
]

solutions = []

for guess_num, x in enumerate(initial_guesses):
    print(f"\nStarting Newton's Method from guess {guess_num+1}: {x}")
    for i in range(1, 21):  # 20 iterations should be enough
        delta = np.linalg.solve(DF(x), F(x))
        x = x - delta
        print(f"Iter {i:2d}: x = {x}, |F(x)|_inf = {np.linalg.norm(F(x), np.inf):.2e}")
        if np.linalg.norm(F(x), np.inf) < 1e-12:
            print("Converged!\n")
            break
    solutions.append(x)
    print(f"Final solution from guess {guess_num+1}: x = {x}")
    print(f"Residual: F(x) = {F(x)}")
    print(f"Backward error (|F(x)|_inf): {np.linalg.norm(F(x), np.inf):.2e}")
    print("-"*40)

##################################################################################
# Print both solutions together for clarity
##################################################################################

print("\nBoth solutions found by Newton's method:")
for i, x in enumerate(solutions, 1):
    print(f"Solution {i}: x = {x}, F(x) = {F(x)}, |F(x)|_inf = {np.linalg.norm(F(x), np.inf):.2e}")



F([1,-1,2]) = [25.  7. 12.]
F([3,5,-4]) = [57. 51. 72.]
DF([1,-1,2]) =
 [[ 0. -2. 18.]
 [ 2. -4.  8.]
 [-6. -2. 12.]]
DF([3,5,-4]) =
 [[  8.  10. -18.]
 [  6.   8. -16.]
 [  6.  10. -24.]]

Starting Newton's Method from guess 1: [2. 2. 2.]
Iter  1: x = [ 3.875 11.75  -2.25 ], |F(x)|_inf = 1.60e+02
Iter  2: x = [ 0.32173401  7.07281854 -1.51600975], |F(x)|_inf = 6.14e+01
Iter  3: x = [ 2.20171711  3.94361011 -1.71675252], |F(x)|_inf = 2.05e+01
Iter  4: x = [ 2.67476582  1.668842   -1.41125491], |F(x)|_inf = 6.13e+00
Iter  5: x = [ 2.02965001  1.43358354 -1.08898256], |F(x)|_inf = 1.62e+00
Iter  6: x = [ 2.02505537  1.03538322 -1.01660247], |F(x)|_inf = 1.74e-01
Iter  7: x = [ 2.00028733  1.00102719 -1.00029378], |F(x)|_inf = 3.82e-03
Iter  8: x = [ 2.00000019  1.00000036 -1.00000014], |F(x)|_inf = 1.56e-06
Iter  9: x = [ 2.  1. -1.], |F(x)|_inf = 2.93e-13
Converged!

Final solution from guess 1: x = [ 2.  1. -1.]
Residual: F(x) = [2.59348099e-13 2.04281037e-13 2.93098879e-13]
Backward e

#2.7.5 (b)

In [21]:
#2.7.5 (b)

import numpy as np
import scipy
from scipy.optimize import fsolve

# Define the radius
R = 5.0

# Define the centers of the spheres
C1 = np.array([1., -2., 0.])
C2 = np.array([-2., 2., -1.])
C3 = np.array([4., -2., 3.])

# F(x) represents the system of equations for the three spheres
# (x - cx)^2 + (y - cy)^2 + (z - cz)^2 - R^2 = 0
F = lambda x : np.array( [
                            ( x[0] - C1[0] )**2 + ( x[1] - C1[1] )**2  + ( x[2] - C1[2] )**2  - R**2,
                            ( x[0] - C2[0] )**2 + ( x[1] - C2[1] )**2  + ( x[2] - C2[2] )**2  - R**2,
                            ( x[0] - C3[0] )**2 + ( x[1] - C3[1] )**2  + ( x[2] - C3[2] )**2  - R**2
                          ] )

# This is the Jacobian of F
DF = lambda x : np.array([
    [ 2. * ( x[0] - C1[0] ), 2. * ( x[1] - C1[1] ), 2. * ( x[2] - C1[2] ) ],
    [ 2. * ( x[0] - C2[0] ), 2. * ( x[1] - C2[1] ), 2. * ( x[2] - C2[2] ) ],
    [ 2. * ( x[0] - C3[0] ), 2. * ( x[1] - C3[1] ), 2. * ( x[2] - C3[2] ) ]
])

print("--- Using scipy.optimize.fsolve to find approximate solutions ---")

# Take an initial guess (e.g., origin)
x_guess1 = np.array( [ 0., 0., 0. ] )
sol1 = scipy.optimize.fsolve( F, x_guess1 )

print( "\nSolution 1 (from fsolve):" )
print( "x = [", f"{sol1[0]:+20.16f}", "]")
print( "    [", f"{sol1[1]:+20.16f}", "]")
print( "    [", f"{sol1[2]:+20.16f}", "]")
print( "Backward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(sol1),np.inf):7.2e}")

# Take another initial guess to find a potentially different solution
# Choose a guess far from the first solution or near where you expect another solution
x_guess2 = np.array( [ 5., 5., 5. ] ) # A different arbitrary guess
sol2 = scipy.optimize.fsolve( F, x_guess2 )

print( "\nSolution 2 (from fsolve):" )
print( "x = [", f"{sol2[0]:+20.16f}", "]")
print( "    [", f"{sol2[1]:+20.16f}", "]")
print( "    [", f"{sol2[2]:+20.16f}", "]")
print( "Backward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(sol2),np.inf):7.2e}")

# If sol1 and sol2 are very close, try another initial guess for sol2
if np.linalg.norm(sol1 - sol2, np.inf) < 1e-6:
    print("\nNote: fsolve converged to the same solution with the second guess.")
    print("Trying another initial guess for Solution 2...")
    x_guess3 = np.array([-5., -5., -5.]) # Try a more distant guess
    sol2 = scipy.optimize.fsolve(F, x_guess3)
    print("\nSolution 2 (from fsolve, new guess):")
    print( "x = [", f"{sol2[0]:+20.16f}", "]")
    print( "    [", f"{sol2[1]:+20.16f}", "]")
    print( "    [", f"{sol2[2]:+20.16f}", "]")
    print( "Backward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(sol2),np.inf):7.2e}")


# --- Multivariate Newton's Method ---
print("\n--- Applying Multivariate Newton's Method ---")

# Let's use the solutions found by fsolve as our target exact solutions for Newton's method
# (We don't know the "exact" solutions analytically for this new problem,
# so fsolve's highly accurate results serve as our reference `x_` values)
exact_sol_1 = sol1
exact_sol_2 = sol2

# Test Newton's method starting near sol1
initial_guess_newton_1 = np.array([sol1[0] - 0.2, sol1[1] + 0.1, sol1[2] + 0.1]) # Start near first center
print(f"\nNewton's Method for Solution 1 (target: {exact_sol_1})")
current_x = initial_guess_newton_1

print( f"{0:2d}", "[", f"{current_x[0]:+18.14f}", f"{current_x[1]:+18.14f}",
       f"{current_x[2]:+18.14f}",
       "]", f"{np.linalg.norm( current_x - exact_sol_1, np.inf):4.1e}",
       f"{np.linalg.norm( F(current_x), np.inf):4.1e}" )

for i in range(1, 8): # 8 iterations should be enough for quadratic convergence
    # Newton's method update
    try:
        delta_x = np.linalg.solve( DF(current_x), F(current_x) )
        current_x = current_x - delta_x
    except np.linalg.LinAlgError:
        print(f"Warning: Singular Jacobian at iteration {i}. Newton's method stopped.")
        break

    print( f"{i:2d}", "[", f"{current_x[0]:+18.14f}",
           f"{current_x[1]:+18.14f}", f"{current_x[2]:+18.14f}",
           "]", f"{np.linalg.norm( current_x - exact_sol_1, np.inf):4.1e}",
           f"{np.linalg.norm( F(current_x), np.inf):4.1e}" )

print( "\nx_final = [", f"{current_x[0]:+18.14f}", "]",
       "      x* = [", f"{exact_sol_1[0]:+18.14f}", "]")
print( "          [", f"{current_x[1]:+18.14f}", "]",
       "           [", f"{exact_sol_1[1]:+18.14f}", "]")
print( "          [", f"{current_x[2]:+18.14f}", "]",
       "           [", f"{exact_sol_1[2]:+18.14f}", "]")
print( "Forward  error: || x - x* ||_oo = ",
       f"{np.linalg.norm(current_x - exact_sol_1, np.inf):7.2e}",
       "\nBackward error: || F(x) ||_oo    = ",
       f"{np.linalg.norm(F(current_x),np.inf):7.2e}")
print("\n")


# Test Newton's method starting near sol2
initial_guess_newton_2 =  np.array([sol2[0] + 0.1, sol2[1] - 0.1, sol2[2] - 0.2]) # Start near second center
print(f"\nNewton's Method for Solution 2 (target: {exact_sol_2})")
current_x = initial_guess_newton_2

print( f"{0:2d}", "[", f"{current_x[0]:+18.14f}", f"{current_x[1]:+18.14f}",
       f"{current_x[2]:+18.14f}",
       "]", f"{np.linalg.norm( current_x - exact_sol_2, np.inf):4.1e}",
       f"{np.linalg.norm( F(current_x), np.inf):4.1e}" )

for i in range(1, 8): # 8 iterations should be enough for quadratic convergence
    # Newton's method update
    try:
        delta_x = np.linalg.solve( DF(current_x), F(current_x) )
        current_x = current_x - delta_x
    except np.linalg.LinAlgError:
        print(f"Warning: Singular Jacobian at iteration {i}. Newton's method stopped.")
        break

    print( f"{i:2d}", "[", f"{current_x[0]:+18.14f}",
           f"{current_x[1]:+18.14f}", f"{current_x[2]:+18.14f}",
           "]", f"{np.linalg.norm( current_x - exact_sol_2, np.inf):4.1e}",
           f"{np.linalg.norm( F(current_x), np.inf):4.1e}" )

print( "\nx_final = [", f"{current_x[0]:+18.14f}", "]",
       "      x* = [", f"{exact_sol_2[0]:+18.14f}", "]")
print( "          [", f"{current_x[1]:+18.14f}", "]",
       "           [", f"{exact_sol_2[1]:+18.14f}", "]")
print( "          [", f"{current_x[2]:+18.14f}", "]",
       "           [", f"{exact_sol_2[2]:+18.14f}", "]")
print( "Forward  error: || x - x* ||_oo = ",
       f"{np.linalg.norm(current_x - exact_sol_2, np.inf):7.2e}",
       "\nBackward error: || F(x) ||_oo    = ",
       f"{np.linalg.norm(F(current_x),np.inf):7.2e}")
print("\n")

--- Using scipy.optimize.fsolve to find approximate solutions ---

Solution 1 (from fsolve):
x = [  +1.8888888888888751 ]
    [  +2.4444444444444366 ]
    [  +2.1111111111111254 ]
Backward error: || F(x) ||_oo   =  3.55e-14

Solution 2 (from fsolve):
x = [  +0.9999999999997231 ]
    [  +1.9999999999998621 ]
    [  +3.0000000000002771 ]
Backward error: || F(x) ||_oo   =  5.61e-13

--- Applying Multivariate Newton's Method ---

Newton's Method for Solution 1 (target: [1.88888889 2.44444444 2.11111111])
 0 [  +1.68888888888888  +2.54444444444444  +2.21111111111113 ] 2.0e-01 1.6e+00
 1 [  +1.92888888888890  +2.46444444444445  +2.07111111111110 ] 4.0e-02 8.4e-02
 2 [  +1.89054026503568  +2.44527013251784  +2.10945973496432 ] 1.7e-03 3.3e-03
 3 [  +1.88889194545550  +2.44444597272775  +2.11110805454450 ] 3.1e-06 6.1e-06
 4 [  +1.88888888889940  +2.44444444444970  +2.11111111110060 ] 1.1e-11 2.1e-11
 5 [  +1.88888888888889  +2.44444444444444  +2.11111111111111 ] 1.4e-14 3.6e-15
 6 [  +1.88888

#2.7.7.b

In [30]:
#2.7.7.b
F = lambda x : np.array([
    x[0]**2 + 4*x[1]**2 - 4,
    4*x[0]**2 + x[1]**2 - 4
])

# Per EX.2.7.3.b, we have four exact solution x1 and 2, let's trying putting in two of those
val = 2/np.sqrt(5)
x1 = np.array([+val, +val])
x2 = np.array([+val, -val])
x3 = np.array([-val, +val])
x4 = np.array([-val, -val])

# Let us check that || F(x1) ||_oo and || F(x2) ||_oo are small
print( "|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}" )
print( "|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}" )
print( "|| F(x3) ||_oo =", f"{np.linalg.norm(F(x3),np.inf):.2E}" )
print( "|| F(x4) ||_oo =", f"{np.linalg.norm(F(x4),np.inf):.2E}" )


for x, x_ in zip( [ np.array( [ 0.9, 0.9 ] ), np.array( [ 0.9, -0.9 ] ), np.array([-0.9, 0.9]), np.array([-0.9, -0.9])],
                  [ x1, x2, x3, x4 ] ):
  A = np.eye(2,2)

  print( f"{0:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
        "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
        f"{np.linalg.norm( F(x), np.inf):4.1e}" )
  tol = 1e-12
  for i in range(1,12):

    x0 = x
    x = x - np.linalg.solve( A, F(x) )
    Delta = ( F(x) - F(x0) )
    delta = x - x0
    if np.linalg.norm(F(x), np.inf) < tol or np.linalg.norm(delta) < tol:
      break                          # we’re converged – stop iterating

    A = A + np.outer ( ( Delta - ( A @ delta ) ), delta / (delta.T @ delta) )
    denom = delta.T @ delta
    if np.abs(denom) < 1e-14:          # step is (numerically) zero – skip update
      continue


    print( f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
            "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
            f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
          "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
          "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
          "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")
  print("\n")


|| F(x1) ||_oo = 4.44E-16
|| F(x2) ||_oo = 4.44E-16
|| F(x3) ||_oo = 4.44E-16
|| F(x4) ||_oo = 4.44E-16
 0 [  +0.9000000000000000  +0.9000000000000000 ] 5.6e-03 5.0e-02
 1 [  +0.8499999999999993  +0.8499999999999993 ] 4.4e-02 3.9e-01
 2 [  +0.8942857142857142  +0.8942857142857142 ] 1.4e-04 1.3e-03
 3 [  +0.8944307944307944  +0.8944307944307944 ] 3.6e-06 3.2e-05
 4 [  +0.8944271907149062  +0.8944271907149062 ] 2.9e-10 2.5e-09

x = [  +0.8944271909999153 ]     x* = [  +0.8944271909999159 ]
    [  +0.8944271909999153 ]          [  +0.8944271909999159 ]
forward  error: || x - x* ||_oo =  5.55e-16 
backward error: || F(x) ||_oo   =  5.33e-15


 0 [  +0.9000000000000000  -0.9000000000000000 ] 5.6e-03 5.0e-02
 1 [  +0.8499999999999993  -0.9500000000000007 ] 5.6e-02 3.3e-01
 2 [  +2.1800000000000188  -1.7800000000000131 ] 1.3e+00 1.8e+01
 3 [  +0.8837598967064773  -0.8864696273230748 ] 1.1e-02 9.0e-02
 4 [  +0.8897919410850174  -0.8922539136679234 ] 4.6e-03 3.7e-02
 5 [  +0.8940007713048937  -

#2.7.7.c

In [33]:
#2.7.7.c

F = lambda x: np.array([
    x[0]**2 - 4*x[1]**2 - 4,           #  u² − 4v² − 4
    (x[0] - 1)**2 + x[1]**2 - 4        # (u−1)² + v² − 4
])

# Per EX.2.7.3.c, we have two exact solution x1 and 2 such that
x1 = np.array([ (4/5)*(1+sqrt(6)),  +(1/5)*sqrt(3+8*sqrt(6)) ])
x2 = np.array([ (4/5)*(1+sqrt(6)),  -(1/5)*sqrt(3+8*sqrt(6)) ])

# Let us check that || F(x1) ||_oo and || F(x2) ||_oo are small
print( "|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}" )
print( "|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}" )

for x, x_ in zip( [ np.array( [ 2.7, 0.9 ] ), np.array( [ 2.7, -0.9 ] ) ],
                  [ x1, x2 ] ):
  A = np.eye(2,2)

  print( f"{0:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
        "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
        f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  for i in range(1,12):

    x0 = x
    x = x - np.linalg.solve( A, F(x) )
    Delta = ( F(x) - F(x0) )
    delta = x - x0
    A = A + np.outer ( ( Delta - ( A @ delta ) ), delta / (delta.T @ delta) )

    print( f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
            "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
            f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
          "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
          "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
          "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")
  print("\n")

|| F(x1) ||_oo = 8.88E-16
|| F(x2) ||_oo = 8.88E-16
 0 [  +2.7000000000000002  +0.9000000000000000 ] 6.0e-02 3.0e-01
 1 [  +2.6499999999999995  +1.1999999999999993 ] 2.5e-01 2.7e+00
 2 [  +3.5604494382022409  +1.1459550561797760 ] 8.0e-01 3.9e+00
 3 [  +2.6940678610893576  +0.9293568291753278 ] 6.6e-02 2.7e-01
 4 [  +2.7488775055838390  +0.9466233734612807 ] 1.1e-02 4.5e-02
 5 [  +2.7599355988996486  +0.9507587235087386 ] 3.4e-04 1.5e-03
 6 [  +2.7596060091151258  +0.9507005710433166 ] 1.4e-05 9.9e-05
 7 [  +2.7595929535370542  +0.9507031016114047 ] 1.2e-06 7.7e-06
 8 [  +2.7595917827450727  +0.9507032770400350 ] 1.1e-08 7.7e-08
 9 [  +2.7595917942250106  +0.9507032753130980 ] 1.5e-12 1.0e-11
10 [  +2.7595917942265427  +0.9507032753128690 ] 1.1e-16 1.8e-15
11 [  +2.7595917942265427  +0.9507032753128691 ] 0.0e+00 8.9e-16

x = [  +2.7595917942265427 ]     x* = [  +2.7595917942265427 ]
    [  +0.9507032753128691 ]          [  +0.9507032753128691 ]
forward  error: || x - x* ||_oo =  0.00e+

#2.7.8.b

In [35]:
#2.7.8.b
F = lambda x : np.array([
    x[0]**2 + 4*x[1]**2 - 4,
    4*x[0]**2 + x[1]**2 - 4
])

# Per EX.2.7.3.b, we have four exact solution x1 and 2, let's trying putting in two of those
val = 2/np.sqrt(5)
x1 = np.array([+val, +val])
x2 = np.array([+val, -val])
x3 = np.array([-val, +val])
x4 = np.array([-val, -val])

# Let us check that || F(x1) ||_oo and || F(x2) ||_oo are small
print( "|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}" )
print( "|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}" )
print( "|| F(x3) ||_oo =", f"{np.linalg.norm(F(x3),np.inf):.2E}" )
print( "|| F(x4) ||_oo =", f"{np.linalg.norm(F(x4),np.inf):.2E}" )


for x, x_ in zip( [ np.array( [ 0.9, 0.9 ] ), np.array( [ 0.9, -0.9 ] ), np.array([-0.9, 0.9]), np.array([-0.9, -0.9])],
                  [ x1, x2, x3, x4 ] ):
  B = np.eye(2,2)

  print( f"{0:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
        "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
        f"{np.linalg.norm( F(x), np.inf):4.1e}" )
  tol = 1e-12
  for i in range(1,12):

    x0 = x
    x = x - B @ F(x)
    Delta = ( F(x) - F(x0) )
    delta = x - x0
    if np.linalg.norm(F(x), np.inf) < tol or np.linalg.norm(delta) < tol:
      break                          # we’re converged – stop iterating

    B = B + np.outer ( ( delta - ( B @ Delta ) ), ( delta.T @ B ) / (delta.T @ ( B @ Delta) ) )
    denom = delta.T @ delta
    if np.abs(denom) < 1e-14:          # step is (numerically) zero – skip update
      continue


    print( f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
            "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
            f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
          "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
          "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
          "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")
  print("\n")


|| F(x1) ||_oo = 4.44E-16
|| F(x2) ||_oo = 4.44E-16
|| F(x3) ||_oo = 4.44E-16
|| F(x4) ||_oo = 4.44E-16
 0 [  +0.9000000000000000  +0.9000000000000000 ] 5.6e-03 5.0e-02
 1 [  +0.8499999999999993  +0.8499999999999993 ] 4.4e-02 3.9e-01
 2 [  +0.8942857142857142  +0.8942857142857142 ] 1.4e-04 1.3e-03
 3 [  +0.8944307944307944  +0.8944307944307944 ] 3.6e-06 3.2e-05
 4 [  +0.8944271907149062  +0.8944271907149062 ] 2.9e-10 2.5e-09

x = [  +0.8944271909999153 ]     x* = [  +0.8944271909999159 ]
    [  +0.8944271909999153 ]          [  +0.8944271909999159 ]
forward  error: || x - x* ||_oo =  5.55e-16 
backward error: || F(x) ||_oo   =  5.33e-15


 0 [  +0.9000000000000000  -0.9000000000000000 ] 5.6e-03 5.0e-02
 1 [  +0.8499999999999993  -0.9500000000000007 ] 5.6e-02 3.3e-01
 2 [  +2.1800000000000184  -1.7800000000000131 ] 1.3e+00 1.8e+01
 3 [  +0.8837598967065197  -0.8864696273231654 ] 1.1e-02 9.0e-02
 4 [  +0.8897919410850418  -0.8922539136679343 ] 4.6e-03 3.7e-02
 5 [  +0.8940007713049065  -

#2.7.8.c


In [36]:
#2.7.8.c
F = lambda x: np.array([
    x[0]**2 - 4*x[1]**2 - 4,           #  u² − 4v² − 4
    (x[0] - 1)**2 + x[1]**2 - 4        # (u−1)² + v² − 4
])

# Per EX.2.7.3.c, we have two exact solution x1 and 2 such that
x1 = np.array([ (4/5)*(1+sqrt(6)),  +(1/5)*sqrt(3+8*sqrt(6)) ])
x2 = np.array([ (4/5)*(1+sqrt(6)),  -(1/5)*sqrt(3+8*sqrt(6)) ])

# Let us check that || F(x1) ||_oo and || F(x2) ||_oo are small
print( "|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}" )
print( "|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}" )

for x, x_ in zip( [ np.array( [ 2.7, 0.9 ] ), np.array( [ 2.7, -0.9 ] ) ],
                  [ x1, x2 ] ):
  B = np.eye(2,2)

  print( f"{0:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
        "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
        f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  for i in range(1,12):

    x0 = x
    x = x - B @ F(x)
    Delta = ( F(x) - F(x0) )
    delta = x - x0
    B = B + np.outer ( ( delta - ( B @ Delta ) ), ( delta.T @ B ) / (delta.T @ ( B @ Delta) ) )

    print( f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
            "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
            f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
          "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
          "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
          "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")
  print("\n")

|| F(x1) ||_oo = 8.88E-16
|| F(x2) ||_oo = 8.88E-16
 0 [  +2.7000000000000002  +0.9000000000000000 ] 6.0e-02 3.0e-01
 1 [  +2.6499999999999995  +1.1999999999999993 ] 2.5e-01 2.7e+00
 2 [  +3.5604494382022409  +1.1459550561797760 ] 8.0e-01 3.9e+00
 3 [  +2.6940678610893567  +0.9293568291753280 ] 6.6e-02 2.7e-01
 4 [  +2.7488775055838386  +0.9466233734612806 ] 1.1e-02 4.5e-02
 5 [  +2.7599355988996486  +0.9507587235087385 ] 3.4e-04 1.5e-03
 6 [  +2.7596060091151258  +0.9507005710433167 ] 1.4e-05 9.9e-05
 7 [  +2.7595929535370542  +0.9507031016114048 ] 1.2e-06 7.7e-06
 8 [  +2.7595917827450727  +0.9507032770400350 ] 1.1e-08 7.7e-08
 9 [  +2.7595917942250106  +0.9507032753130980 ] 1.5e-12 1.0e-11
10 [  +2.7595917942265427  +0.9507032753128690 ] 1.1e-16 1.8e-15
11 [  +2.7595917942265427  +0.9507032753128691 ] 0.0e+00 8.9e-16

x = [  +2.7595917942265427 ]     x* = [  +2.7595917942265427 ]
    [  +0.9507032753128691 ]          [  +0.9507032753128691 ]
forward  error: || x - x* ||_oo =  0.00e+